spring.application.name=work.team

server.port=8083
springdoc.swagger-ui.path=/swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/work_team
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}

external.user.service.baseurl=http://localhost:8081
external.task.service.baseurl=http://localhost:8082

logging.level.org.springframework.web=DEBUG